unstable_features = true
binop_separator = "Back"
edition = "2021"
fn_single_line = true
format_strings = true
max_width = 80
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
wrap_comments = true
skip_macro_invocations = ["trace", "debug", "info", "warn", "error"]
